name: 'Docker Login with Verification'
description: 'Login to Docker Hub and verify the login with user information'
inputs:
  username:
    description: 'Docker Hub username'
    required: true
  password:
    description: 'Docker Hub password'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ inputs.username }}
        password: ${{ inputs.password }}
    
    - name: Verify Docker login
      shell: bash
      run: |
        echo "Docker login successful!"
        echo "Current Docker user: $(docker system info | grep Username || echo 'Not available')"
        