name: 'Docker Login with Verification'
description: 'Login to Docker Hub and verify the login with user information'
runs:
  using: 'composite'
  steps:
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Verify Docker login
      shell: bash
      run: |
        echo "Docker login successful!"
        echo "Current Docker user: $(docker system info | grep Username || echo 'Not available')"