name: Build Docker Images

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  build:
    uses: ./.github/workflows/build-services.yml
    with:
      tag: ${{ github.sha }}
    secrets: inherit