name: Build Services (Reusable)

on:
  workflow_call:
    inputs:
      tag:
        description: 'Tag to apply to images'
        required: true
        type: string

jobs:
  # Generate services list for matrix
  setup:
    name: Setup services matrix
    runs-on: ubuntu-latest
    outputs:
      services: ${{ steps.setup-services.outputs.services }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup services matrix
        id: setup-services
        uses: ./.github/actions/setup-services-matrix

  # Build for both architectures natively  
  build:
    name: Build ${{ matrix.service }} (${{ matrix.arch }})
    runs-on: ${{ matrix.runner }}
    needs: setup
    strategy:
      matrix:
        service: ${{ fromJson(needs.setup.outputs.services) }}
        arch: [amd64, arm64]
        include:
          - arch: amd64
            runner: ubuntu-latest
            platform: linux/amd64
          - arch: arm64
            runner: ubuntu-24.04-arm64
            platform: linux/arm64
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Build Docker Image
        uses: ./.github/actions/build-docker-image
        with:
          service_name: ${{ matrix.service }}
          tag: ${{ inputs.tag }}-${{ matrix.arch }}
          platform: ${{ matrix.platform }}
          docker_username: ${{ secrets.DOCKER_USERNAME }}
          docker_password: ${{ secrets.DOCKER_PASSWORD }}

  # Create multiarch manifests
  create-multiarch:
    name: Create multiarch manifest for ${{ matrix.service }}
    runs-on: ubuntu-latest
    needs: [setup, build]
    strategy:
      matrix:
        service: ${{ fromJson(needs.setup.outputs.services) }}
    steps:
      
      - name: Docker Login
        uses: ./.github/actions/docker-login
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Create multiarch manifest
        run: |
          AMD64_TAG="audius/pedalboard:${{ matrix.service }}-${{ inputs.tag }}-amd64"
          ARM64_TAG="audius/pedalboard:${{ matrix.service }}-${{ inputs.tag }}-arm64"
          MULTIARCH_TAG="audius/pedalboard:${{ matrix.service }}-${{ inputs.tag }}"
          
          docker buildx imagetools create \
            "$AMD64_TAG" \
            "$ARM64_TAG" \
            --tag "$MULTIARCH_TAG"
          