name: Edge Release

on:
  workflow_run:
    workflows: ["Build Docker Images"]
    types: [completed]
    branches: [main]

concurrency:
  group: edge-release
  cancel-in-progress: false

jobs:
  retag:
    if: github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [
          verified-notifications,
          crm,
          archiver,
          staking,
          trending-challenge-rewards,
          mri,
          relay,
          solana-relay,
          anti-abuse-oracle
        ]
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Docker Login
        uses: ./.github/actions/docker-login
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Retag as edge
        run: |
          SOURCE_TAG="audius/pedalboard:${{ matrix.service }}-${{ github.event.workflow_run.head_sha }}"
          EDGE_TAG="audius/pedalboard:${{ matrix.service }}-edge"
          docker buildx imagetools create "$SOURCE_TAG" --tag "$EDGE_TAG"